In [ ]:
import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import norm

In [ ]:
def d1(S,K,r,Stdev,T):
  return (np.log(S/K) + (r + Stdev**2/2)*T)/(Stdev*np.sqrt(T))

In [ ]:
def d2(S,K,r,Stdev,T):
  return (np.log(S/K) + (r - Stdev**2/2)*T)/(Stdev*np.sqrt(T))

In [ ]:
def BSM(S,K,r,Stdev,T):
  return (S*norm.cdf(d1(S,K,r,Stdev,T))) - (K*np.exp(-r*T)*norm.cdf(d2(S,K,r,Stdev,T)))

In [ ]:
data = yf.download('^NSEI', start = '2020-01-01')['Close']
data

/tmp/ipykernel_8773/3336169343.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('^NSEI', start = '2020-01-01')['Close']
[*********************100%***********************]  1 of 1 completed

Ticker             ^NSEI
Date
2020-01-01  12182.500000
2020-01-02  12282.200195
2020-01-03  12226.650391
2020-01-06  11993.049805
2020-01-07  12052.950195
...                  ...
2026-03-13  23151.099609
2026-03-16  23408.800781
2026-03-17  23581.150391
2026-03-18  23777.800781
2026-03-20  23234.300781

[1539 rows x 1 columns]

In [ ]:
S = data.iloc[-1]
S

Ticker
^NSEI    23234.300781
Name: 2026-03-20 00:00:00, dtype: float64

In [ ]:
r = 0.02
K = 23000
T = 5/365
#Std_dev = 0.29

In [ ]:
market_price = 386.6 # call option price at strike

#We will start sigma at 10% and keep increasing it till we solve the equation
sigma_test = 0.1
model_price = 0

while model_price < market_price:
  sigma_test = sigma_test + 0.001
  model_price = BSM(S,K,r,sigma_test,T)[0]

print(f"The implied volatility is {sigma_test*100}%")

/tmp/ipykernel_8773/663779012.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_price = BSM(S,K,r,sigma_test,T)[0]

The implied volatility is 23.00000000000001%